### ISSUE TITLE
[feature request] City stuff

### ISSUE THREAD

**Issue by lublak** [TyrellPlayz/TyrellPlayz-City-Mod#13]
Since I play around with your mod i have more and more ideas.

- City Bin as Bin
A chest that deletes items on close

- Make the street based on concrete
To run faster on the street

- Are there recipes?
Yes? Than integrate it in jei?
No? Make some

- Better Street Texture
Make more uneven
I can make some if you want.

- Better Manhole Texture
Like this:
![grafik](https://user-images.githubusercontent.com/44057030/48792759-5f9bf880-ecf5-11e8-963b-387d26ffcc43.png)
Here you can get it:
----> ![manhole cover](https://user-images.githubusercontent.com/44057030/48792804-7c383080-ecf5-11e8-917b-842715f1d7a4.png) <----

- Roadpainter
Roadpainter can auto paint "Inner Corner"
"If roadpainter paint a "Unbroken Angle" and if the block is Tarmac Road it can be auto painted (or removed if you you remove "Unbroken Angle")
But i think the most people think like minecraft (not diagonal). So its not important.

- Traffic Light
Arrow Traffic Lights
"You can only drive right on green traffic light"
"You can only drive left on green traffic light"
"You can only drive straight on green traffic light"
I think its only a texture based thing

- Road
Roads can be a little bit lower than a normal block.
Or extra "Lower Roads"?
That can make the sidewalk easier.
![grafik](https://user-images.githubusercontent.com/44057030/48792999-f7014b80-ecf5-11e8-9f4b-e8d730015f63.png)

- Roadpainter extra painting
Just add an T without one leg
Like:
![grafik](https://user-images.githubusercontent.com/44057030/48791659-80168380-ecf2-11e8-9339-5a933406c712.png)
for
![grafik](https://user-images.githubusercontent.com/44057030/48794509-7db82780-ecfa-11e8-8693-462aea237e42.png)

And in wide:
![grafik](https://user-images.githubusercontent.com/44057030/48791779-d4216800-ecf2-11e8-94c8-30d39032a9d4.png)
for
![grafik](https://user-images.githubusercontent.com/44057030/48794397-22863500-ecfa-11e8-9610-2e781a5b1fbf.png)

- Make more colors
![grafik](https://user-images.githubusercontent.com/44057030/48792073-9ffa7700-ecf3-11e8-9f28-18a4881ed6fb.png)
![grafik](https://user-images.githubusercontent.com/44057030/48793279-bce47980-ecf6-11e8-8aef-d6e4051793ee.png)

**Comment by TyrellPlayz** [comment]
![2018-11-24_16 00 36](https://user-images.githubusercontent.com/19235911/48964909-266bcd00-f002-11e8-9923-14cd1051066b.png)
