### ISSUE TITLE
[bug] Optfine color issues

### ISSUE THREAD

**Issue by lublak** [TyrellPlayz/TyrellPlayz-City-Mod#15]
I don't think you need support it.
But to be complete i test it:

Without:
<img width="673" alt="javaw_2018-12-03_19-29-09" src="https://user-images.githubusercontent.com/44057030/49393811-91b84c00-f732-11e8-9d4b-da89bee42f37.png">

With:
<img width="611" alt="javaw_2018-12-03_19-34-16" src="https://user-images.githubusercontent.com/44057030/49393815-967d0000-f732-11e8-87af-caa264f5fb10.png">

Works with: 
![grafik](https://user-images.githubusercontent.com/44057030/49393912-e3f96d00-f732-11e8-8ca7-dba38e2dd785.png)

![grafik](https://user-images.githubusercontent.com/44057030/49394001-15723880-f733-11e8-8c33-4aaf26e6ad55.png)

**Comment by TyrellPlayz** [comment]
I had this issue as with optfine but didn't look into the problem and just got rid of optfine, will look into it now.

**Comment by lublak** [comment]
But i think it has a low low priority. I mostly don't use optfine in my modpacks. Because the most mods don't support it.
I just post this issue to be complete.
