### ISSUE TITLE
[bug] Switch Box Texture issue

### ISSUE THREAD

**Issue by lublak** [TyrellPlayz/TyrellPlayz-City-Mod#16]
A simple pixel bug:

![grafik](https://user-images.githubusercontent.com/44057030/49394420-19528a80-f734-11e8-921b-7257f7b9b7a5.png)

**Comment by TyrellPlayz** [comment]
How did I miss that?

**Comment by lublak** [comment]
I don't know but i'm here to find all the bugs 😄
