### ISSUE TITLE
[improvements] Seamless diagonal lines

### ISSUE THREAD

**Issue by lublak** [TyrellPlayz/TyrellPlayz-City-Mod#17]
![grafik](https://user-images.githubusercontent.com/44057030/49398281-22485980-f73e-11e8-8ab8-a75648d70466.png)

looks like:
![grafik](https://user-images.githubusercontent.com/44057030/49398421-9daa0b00-f73e-11e8-8a41-cbcf0fe44346.png)

**Comment by TyrellPlayz** [comment]
I can try to fix it by making all the road textures 32x32.
