### ISSUE TITLE
[bug] Slope destroys not complete

### ISSUE THREAD

**Issue by lublak** [TyrellPlayz/TyrellPlayz-City-Mod#18]
![grafik](https://user-images.githubusercontent.com/44057030/49398719-828bcb00-f73f-11e8-9d09-869e7fd163a8.png)

each can destroy by itself
![grafik](https://user-images.githubusercontent.com/44057030/49398798-bcf56800-f73f-11e8-8b99-9469a650fff4.png)

**Comment by TyrellPlayz** [comment]
I designed it to work like that until I come up with a better way.

**Comment by lublak** [comment]
Ah okay It looks like a mistake, so I posted it.
I try to test your mod to find all the bugs.

**Comment by TyrellPlayz** [comment]
Thanks for your help 😃
