### ISSUE TITLE
Signal box switches to yellow in-between every stage, even during red -> green

### ISSUE THREAD

**Issue by JadianRadiator** [TyrellPlayz/TyrellPlayz-City-Mod#22]
Signal box switches to yellow in-between every stage.
Even when transitioning a light from red to green.
I would like to request that you change it to make it more realistic.
Either a tick-box option whether to do yellow between states,
or (though I would not recommend it) a third "yellow" option and have us control it outright as part of the state.

**Comment by TyrellPlayz** [comment]
more realistic? If you read the description on curse forge any road related things are based on Australia Roads. Traffic lights there switch to yellow before red and green. 

Some time soon you can choose how long the yellow stage with show for. Set it to 0 and it will skip the yellow.
