### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SilexW** [TyrellPlayz/TyrellPlayz-City-Mod#5]
first time running mc with your awesome mod and i got a crash, any way to fix it?

follows the crash report:

https://paste.dimdev.org/iqeyijiqow.mccrash

**Comment by TyrellPlayz** [comment]
Fixed

**Comment by SilexW** [comment]
tried the new version and get another crash
sorry to bother you

https://paste.dimdev.org/editajagub.mccrash

**Comment by TyrellPlayz** [comment]
Hopefully fixed. Please want for 0.2.2 alpha to be reapproved. Thanks for your help.

**Comment by SilexW** [comment]
working fine with the new update.
thank you
